
// This file was autogenerated by PeakRDL-uvm
package reg_models_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - simple_spi_regs::SPCR
    class simple_spi_regs__SPCR extends uvm_reg;
        rand uvm_reg_field SPR;
        rand uvm_reg_field CPHA;
        rand uvm_reg_field CPOL;
        rand uvm_reg_field MSTR;
        rand uvm_reg_field Reserved;
        rand uvm_reg_field SPE;
        rand uvm_reg_field SPIE;

        function new(string name = "simple_spi_regs__SPCR");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.SPR = new("SPR");
            this.SPR.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
            this.CPHA = new("CPHA");
            this.CPHA.configure(this, 1, 2, "RW", 0, 'h0, 1, 1, 0);
            this.CPOL = new("CPOL");
            this.CPOL.configure(this, 1, 3, "RW", 0, 'h0, 1, 1, 0);
            this.MSTR = new("MSTR");
            this.MSTR.configure(this, 1, 4, "RW", 0, 'h1, 1, 1, 0);
            this.Reserved = new("Reserved");
            this.Reserved.configure(this, 1, 5, "RW", 0, 'h0, 1, 1, 0);
            this.SPE = new("SPE");
            this.SPE.configure(this, 1, 6, "RW", 0, 'h0, 1, 1, 0);
            this.SPIE = new("SPIE");
            this.SPIE.configure(this, 1, 7, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : simple_spi_regs__SPCR

    // reg - simple_spi_regs::SPSR
    class simple_spi_regs__SPSR extends uvm_reg;
        rand uvm_reg_field RFEMPTY;
        rand uvm_reg_field RFFULL;
        rand uvm_reg_field WFEMPTY;
        rand uvm_reg_field WFFULL;
        rand uvm_reg_field Reserved_bits;
        rand uvm_reg_field WCOL;
        rand uvm_reg_field SPIF;

        function new(string name = "simple_spi_regs__SPSR");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.RFEMPTY = new("RFEMPTY");
            this.RFEMPTY.configure(this, 1, 0, "RO", 1, 'h1, 1, 1, 0);
            this.RFFULL = new("RFFULL");
            this.RFFULL.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            this.WFEMPTY = new("WFEMPTY");
            this.WFEMPTY.configure(this, 1, 2, "RO", 1, 'h1, 1, 1, 0);
            this.WFFULL = new("WFFULL");
            this.WFFULL.configure(this, 1, 3, "RO", 1, 'h0, 1, 1, 0);
            this.Reserved_bits = new("Reserved_bits");
            this.Reserved_bits.configure(this, 2, 4, "RO", 1, 'h0, 1, 1, 0);
            this.WCOL = new("WCOL");
            this.WCOL.configure(this, 1, 6, "W1C", 1, 'h0, 1, 1, 0);
            this.SPIF = new("SPIF");
            this.SPIF.configure(this, 1, 7, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : simple_spi_regs__SPSR

    // reg - simple_spi_regs::SPDR
    class simple_spi_regs__SPDR extends uvm_reg;
        rand uvm_reg_field DATA;

        function new(string name = "simple_spi_regs__SPDR");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.DATA = new("DATA");
            this.DATA.configure(this, 8, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : simple_spi_regs__SPDR

    // reg - simple_spi_regs::SPER
    class simple_spi_regs__SPER extends uvm_reg;
        rand uvm_reg_field ESPR;
        rand uvm_reg_field Reserved_ext;
        rand uvm_reg_field ICNT;

        function new(string name = "simple_spi_regs__SPER");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ESPR = new("ESPR");
            this.ESPR.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
            this.Reserved_ext = new("Reserved_ext");
            this.Reserved_ext.configure(this, 4, 2, "RW", 0, 'h0, 1, 1, 0);
            this.ICNT = new("ICNT");
            this.ICNT.configure(this, 2, 6, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : simple_spi_regs__SPER

    // addrmap - simple_spi_regs
    class simple_spi_regs extends uvm_reg_block;
        rand simple_spi_regs__SPCR SPCR;
        rand simple_spi_regs__SPSR SPSR;
        rand simple_spi_regs__SPDR SPDR;
        rand simple_spi_regs__SPER SPER;

        function new(string name = "simple_spi_regs");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 1, UVM_NO_ENDIAN);
            this.SPCR = new("SPCR");
            this.SPCR.configure(this);

            this.SPCR.build();
            this.default_map.add_reg(this.SPCR, 'h0);
            this.SPSR = new("SPSR");
            this.SPSR.configure(this);

            this.SPSR.build();
            this.default_map.add_reg(this.SPSR, 'h1);
            this.SPDR = new("SPDR");
            this.SPDR.configure(this);

            this.SPDR.build();
            this.default_map.add_reg(this.SPDR, 'h2);
            this.SPER = new("SPER");
            this.SPER.configure(this);

            this.SPER.build();
            this.default_map.add_reg(this.SPER, 'h3);
        endfunction : build
    endclass : simple_spi_regs

endpackage: reg_models_pkg
